name: Build and Publish

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag release version'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract the tag version
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            GITHUB_REF=${{ github.event.inputs.tag }}
          fi          
          echo "tag=${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v${{ steps.tag.outputs.tag }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: scripts/build.sh github.com/akecel/gabbro

      - name: Upload Release Assets
        run: |
          cd bin &&
          for FILE in *;
            do
            gh release upload v${{ steps.tag.outputs.tag }} $FILE 
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

