name: Build and Publish 2

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag release version'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract the tag version
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            GITHUB_REF=${{ github.event.inputs.tag }}
          fi          
          echo "tag=${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v${{ steps.tag.outputs.tag }}

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64, windows/arm64'
            package: ''
            name: 'gabbro'
            compress: 'true'
            dest: 'dist'

